### ISSUE TITLE
Remove your creds and reset your pass.

### ISSUE THREAD

**Issue by superhedgy** [dorabz/linkedin-scraper#1]
**@dorabz, you left your LinkedIn Creds in the code.**

**Comment by dorabz** [comment]
Thanks, but that password and email is imaginary. I will put some more obvious fake email in the code.

**Comment by superhedgy** [comment]
Ah okey.. I wasn't sure.
--


*Andreas Georgiou*
Senior Security Consultant | Penetration Tester | CCSC Mentor

*LinkedIn:* linkedin.com/in/andreasgeorgiou/
*Twitter: ***@***.***
*Git: *github.com/superhedgy/
